"""Claude API integration for autonomous trade analysis.

Replaces the manual copy-paste workflow with direct Anthropic SDK calls.
All functions are synchronous — callers use asyncio.to_thread() from background tasks.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

from config import load_config
from services.strategy_service import STRATEGIES, list_strategies

logger = logging.getLogger(__name__)

_client = None

# Hard allow-list for model names. Any call that passes a model not in this set
# will be REWRITTEN to the canonical Sonnet model and logged as an error. This
# is a defense-in-depth safety against accidental Opus usage — every layer of
# the app should use Sonnet only.
_ALLOWED_MODELS = {"claude-sonnet-4-6"}
_CANONICAL_MODEL = "claude-sonnet-4-6"


def _enforce_sonnet_only(original_create):
    """Wrap anthropic.messages.create to block any model outside the allow-list.

    If a disallowed model (e.g. Opus) is requested, the call is rewritten to
    Sonnet, the adaptive-thinking / max-effort flags are stripped (to avoid
    carrying expensive-call settings into the downgraded call), and a loud
    error is logged. This is intentional belt-and-suspenders so a bug in one
    call site cannot burn tokens on Opus.
    """
    def guarded_create(*args, **kwargs):
        requested_model = kwargs.get("model")
        if requested_model and requested_model not in _ALLOWED_MODELS:
            import traceback
            caller = "unknown"
            try:
                stack = traceback.extract_stack(limit=5)
                if len(stack) >= 2:
                    caller = f"{stack[-2].filename.split(chr(92))[-1]}:{stack[-2].lineno}"
            except Exception:
                pass
            logger.error(
                "BLOCKED non-Sonnet model request: requested=%r, rewriting to %s. Caller: %s",
                requested_model, _CANONICAL_MODEL, caller,
            )
            kwargs["model"] = _CANONICAL_MODEL
            # Strip expensive-call settings so a downgraded call doesn't silently
            # use Opus-style parameters against Sonnet.
            kwargs.pop("thinking", None)
            extra = kwargs.get("extra_body")
            if isinstance(extra, dict):
                extra.pop("output_config", None)
                if not extra:
                    kwargs.pop("extra_body", None)
            # Clamp max_tokens too — Opus paths use 16000; Sonnet reasonable cap.
            if kwargs.get("max_tokens", 0) > 4096:
                kwargs["max_tokens"] = 4096
        return original_create(*args, **kwargs)
    return guarded_create


def _get_client():
    global _client
    if _client is not None:
        return _client
    try:
        import anthropic
    except ImportError:
        logger.error("anthropic package not installed — run: pip install anthropic")
        return None
    cfg = load_config()
    api_key = (cfg.claude.api_key or "").strip()
    if not api_key:
        logger.warning("Claude API key not configured in data/config.json")
        return None
    if not api_key.startswith("sk-ant-api"):
        # Reject anything that isn't a real API key — OAuth tokens (sk-ant-oat…),
        # session tokens, or stray strings would otherwise fail obscurely at the
        # first request. Fail loudly at client construction instead.
        logger.error(
            "Claude config key does not look like an API key (expected prefix sk-ant-api). "
            "Refusing to construct client to avoid env-var fallback."
        )
        return None
    # Defense in depth: strip ANTHROPIC_API_KEY from this process's environment
    # before constructing the SDK client. The SDK falls back to that env var
    # when api_key is falsy — and any subprocess we spawn would inherit it.
    # We pass the key explicitly below, so clearing env costs nothing and
    # guarantees the key never escapes the config.json boundary.
    import os
    os.environ.pop("ANTHROPIC_API_KEY", None)
    client = anthropic.Anthropic(api_key=api_key)
    # Wrap messages.create with the Sonnet-only guard
    client.messages.create = _enforce_sonnet_only(client.messages.create)
    _client = client
    return _client


def reset_client():
    """Reset the cached client (call after API key changes)."""
    global _client
    _client = None


def _build_system_prompt() -> str:
    return (
        "You are an expert forex trading analyst integrated into an automated trading platform. "
        "Your role is to evaluate trade signals generated by technical strategies and provide "
        "a second opinion before execution.\n\n"
        "Guidelines:\n"
        "- Be conservative. Only recommend execution when multiple factors align.\n"
        "- Consider risk/reward ratio — prefer trades with R:R >= 1.5.\n"
        "- Flag when price is near major support/resistance levels.\n"
        "- Avoid trades during periods of extreme low or high volatility.\n"
        "- Consider the current trend direction relative to the signal.\n"
        "- CRITICAL: Avoid trading within 30 minutes of high-impact economic events (NFP, FOMC, rate decisions).\n"
        "- Factor market sentiment into your confidence score — if technical and fundamental signals diverge, reduce confidence.\n"
        "- Always respond with valid JSON — no markdown outside the JSON block."
    )


def _extract_text(response) -> str:
    """Extract text from a Claude response, handling thinking blocks.

    With adaptive thinking enabled, response.content may contain both
    'thinking' and 'text' blocks. This returns the first text block.
    """
    for block in response.content:
        if hasattr(block, "text") and block.type == "text":
            return block.text
    # Fallback: find any block with a .text attribute
    for block in response.content:
        if hasattr(block, "text"):
            return block.text
    # Last resort: concatenate thinking blocks (better than crashing)
    for block in response.content:
        if hasattr(block, "thinking") and block.thinking:
            logger.warning("No text block in response — falling back to thinking block")
            return block.thinking
    return ""


def _review_create(client, cfg, system: str, prompt: str, **kwargs):
    """Call Claude for review/evolve/training analysis.

    Previously routed to Opus with adaptive thinking at max effort. That was
    removed as a safety measure — the app is locked to Sonnet-only. This
    function now uses the standard Sonnet model and parameters. The output
    will be less thorough than the old Opus path, but it cannot burn Opus
    tokens.
    """
    return client.messages.create(
        model=cfg.claude.model,
        max_tokens=min(cfg.claude.max_tokens, 4096),
        system=system,
        messages=[{"role": "user", "content": prompt}],
        **kwargs,
    )


def _parse_json_response(text: str) -> dict | list | None:
    """Extract JSON object or array from Claude's response.

    Handles code blocks, raw JSON, and extra trailing content.
    """
    # Try code blocks first
    code_block = re.search(r"```(?:json)?\s*\n?(.*?)```", text, re.DOTALL)
    if code_block:
        json_str = code_block.group(1).strip()
        result = _try_parse_json(json_str)
        if result is not None:
            return result

    # Try the full text as-is
    result = _try_parse_json(text.strip())
    if result is not None:
        return result

    # Find first [ or { and try to parse from there
    for start_char, end_char in [("[", "]"), ("{", "}")]:
        start_idx = text.find(start_char)
        if start_idx == -1:
            continue
        # Find matching closing bracket by counting nesting
        depth = 0
        for i in range(start_idx, len(text)):
            if text[i] == start_char:
                depth += 1
            elif text[i] == end_char:
                depth -= 1
                if depth == 0:
                    json_str = text[start_idx:i + 1]
                    result = _try_parse_json(json_str)
                    if result is not None:
                        return result
                    break

    logger.warning("Could not extract JSON from response (len=%d)", len(text))
    return None


def _try_parse_json(text: str) -> dict | list | None:
    """Try to parse JSON, return None on failure (no logging)."""
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return None


def _format_events(events: list[dict] | None) -> str:
    """Format upcoming economic events for the Claude prompt."""
    if not events:
        return "  None upcoming"
    return "\n".join(
        "  - {title} ({ccy}, {imp} impact) in {mins} min{fc}".format(
            title=e["title"], ccy=e["currency"], imp=e["impact"],
            mins=e.get("minutes_until", "?"),
            fc=f" | Forecast: {e['forecast']}" if e.get("forecast") else "",
        )
        for e in events[:10]
    )


def _format_sentiment(sentiment: dict | None) -> str:
    """Format sentiment data for the Claude prompt."""
    if not sentiment:
        return "No sentiment data available"
    score = sentiment.get("score", 0)
    label = "bullish" if score > 0.2 else "bearish" if score < -0.2 else "neutral"
    reasoning = sentiment.get("reasoning", "")
    age = sentiment.get("age_minutes", "?")
    return f"{label} ({score:+.2f}), {age} min ago. {reasoning}"


def analyze_trade_signal(
    symbol: str,
    timeframe: str,
    strategy_name: str,
    signal_side: str,
    signal_reason: str,
    price: float,
    stop_loss: float | None,
    take_profit: float | None,
    candle_summary: list[dict],
    indicators: dict[str, Any],
    account_equity: float | None = None,
    open_positions: list[dict] | None = None,
    upcoming_events: list[dict] | None = None,
    sentiment: dict | None = None,
) -> dict:
    """Ask Claude to evaluate a trade signal. Returns analysis dict.

    On failure, returns a safe default that skips the trade.
    """
    client = _get_client()
    if client is None:
        return {"confidence": 0.0, "recommendation": "skip", "reasoning": "Claude API not available"}

    cfg = load_config()

    # Build concise candle summary (last 20 candles)
    recent = candle_summary[-20:] if len(candle_summary) > 20 else candle_summary
    candle_text = "\n".join(
        f"  {c.get('time', '?')}: O={c['open']:.5f} H={c['high']:.5f} "
        f"L={c['low']:.5f} C={c['close']:.5f}"
        for c in recent
    )

    indicator_text = "\n".join(f"  {k}: {v}" for k, v in indicators.items())

    position_text = "None"
    if open_positions:
        position_text = "\n".join(
            f"  {p['symbol']} {p['side']} @ {p.get('price', '?')} vol={p.get('volume', '?')}"
            for p in open_positions
        )

    user_prompt = (
        f"Evaluate this trade signal:\n\n"
        f"Symbol: {symbol}\n"
        f"Timeframe: {timeframe}\n"
        f"Strategy: {strategy_name}\n"
        f"Signal: {signal_side.upper()}\n"
        f"Price: {price:.5f}\n"
        f"Stop Loss: {f'{stop_loss:.5f}' if stop_loss else 'not set'}\n"
        f"Take Profit: {f'{take_profit:.5f}' if take_profit else 'not set'}\n"
        f"Reason: {signal_reason}\n\n"
        f"Recent candles ({timeframe}):\n{candle_text}\n\n"
        f"Current indicators:\n{indicator_text}\n\n"
        f"Account equity: {account_equity or 'unknown'}\n"
        f"Open positions:\n{position_text}\n\n"
        f"Upcoming economic events:\n{_format_events(upcoming_events)}\n\n"
        f"Market sentiment: {_format_sentiment(sentiment)}\n\n"
        f"Respond with a JSON object (keep reasoning short - we store and read it):\n"
        f'{{\n'
        f'  "confidence": 0.0-1.0,\n'
        f'  "recommendation": "execute" | "skip" | "wait",\n'
        f'  "adjusted_sl": <float or null>,\n'
        f'  "adjusted_tp": <float or null>,\n'
        f'  "reasoning": "<=200 chars: primary factor driving the decision"\n'
        f'}}'
    )

    try:
        response = client.messages.create(
            model=cfg.claude.model,  # signal generation → fast model (Sonnet)
            max_tokens=cfg.claude.max_tokens,
            temperature=cfg.claude.temperature,
            system=_build_system_prompt(),
            messages=[{"role": "user", "content": user_prompt}],
        )
        text = response.content[0].text
        parsed = _parse_json_response(text)
        if parsed is None:
            return {"confidence": 0.0, "recommendation": "skip", "reasoning": "Could not parse Claude response"}
        # Ensure required fields
        parsed.setdefault("confidence", 0.0)
        parsed.setdefault("recommendation", "skip")
        parsed.setdefault("reasoning", "")
        return parsed
    except Exception as exc:
        logger.error("Claude API error: %s", exc)
        return {"confidence": 0.0, "recommendation": "skip", "reasoning": f"API error: {exc}"}


def analyze_optimization_results(
    symbol: str,
    timeframe: str,
    candle_count: int,
    results_markdown: str,
) -> dict:
    """Send optimization results to Claude for analysis. Returns parsed response."""
    client = _get_client()
    if client is None:
        return {"error": "Claude API not available"}

    cfg = load_config()

    user_prompt = (
        f"Analyze these forex strategy optimization results:\n\n"
        f"Symbol: {symbol}, Timeframe: {timeframe}, Candles: {candle_count}\n\n"
        f"{results_markdown}\n\n"
        f"Respond with a JSON object:\n"
        f'{{\n'
        f'  "analysis": "<your analysis>",\n'
        f'  "best_config": {{"strategy_type": "...", "parameters": {{...}}}},\n'
        f'  "warnings": ["overfitting concerns", ...],\n'
        f'  "refined_suggestions": [{{"strategy_type": "...", "parameters": {{...}}, "rationale": "..."}}]\n'
        f'}}'
    )

    try:
        response = _review_create(client, cfg, _build_system_prompt(), user_prompt)
        text = _extract_text(response)
        parsed = _parse_json_response(text)
        if parsed is None:
            return {"error": "Could not parse Claude response", "raw": text}
        return parsed
    except Exception as exc:
        logger.error("Claude API error: %s", exc)
        return {"error": str(exc)}


def analyze_strategy_performance(scorecard: list[dict], signal_accuracy: dict) -> dict:
    """Ask Claude to review live trading performance and suggest adjustments.

    This is the Phase 3 feedback loop — Claude analyzes actual results
    and recommends strategy rotation or parameter changes.
    """
    client = _get_client()
    if client is None:
        return {"error": "Claude API not available"}

    cfg = load_config()

    if not scorecard:
        return {"error": "No performance data to analyze"}

    scorecard_text = "\n".join(
        "  {name}: {trades} trades, {wr:.1%} win rate, PF={pf:.2f}, "
        "P&L=${pnl:.2f}, MaxDD=${dd:.2f}".format(
            name=s["strategy"], trades=s["trades"], wr=s["win_rate"],
            pf=s["profit_factor"], pnl=s["total_pnl"], dd=s["max_drawdown"],
        )
        for s in scorecard
    )

    accuracy_text = "No confidence data"
    if signal_accuracy.get("total", 0) > 0:
        parts = []
        for level in ("high", "medium", "low"):
            bucket = signal_accuracy.get(f"{level}_confidence", {})
            if bucket.get("count"):
                acc = bucket.get("accuracy")
                parts.append(f"  {level}: {bucket['count']} signals, {acc:.1%} accuracy" if acc is not None else f"  {level}: {bucket['count']} signals")
        accuracy_text = "\n".join(parts) if parts else "No data"

    prompt = (
        "Review the live trading performance of our strategy portfolio:\n\n"
        f"Strategy scorecard:\n{scorecard_text}\n\n"
        f"Signal confidence accuracy:\n{accuracy_text}\n\n"
        "Analyze and respond with JSON:\n"
        '{\n'
        '  "summary": "overall assessment",\n'
        '  "degraded_strategies": ["strategies performing below expectations"],\n'
        '  "strong_strategies": ["strategies performing well"],\n'
        '  "recommendations": [\n'
        '    {"action": "disable|adjust|keep", "strategy": "name", "reason": "why"}\n'
        '  ],\n'
        '  "confidence_calibration": "is Claude confidence predicting outcomes well?"\n'
        '}'
    )

    try:
        response = _review_create(client, cfg, _build_system_prompt(), prompt)
        text = _extract_text(response)
        parsed = _parse_json_response(text)
        if parsed is None:
            return {"error": "Could not parse Claude response", "raw": text}
        return parsed
    except Exception as exc:
        logger.error("Claude API error: %s", exc)
        return {"error": str(exc)}


def analyze_training_iteration(
    strategy_type: str,
    parameters: dict,
    metrics: dict,
    trade_summary: str,
    candle_count: int,
    iteration_number: int,
    previous_metrics: dict | None = None,
    previous_params: dict | None = None,
) -> dict:
    """Analyze a training iteration and suggest parameter adjustments.

    Called after each backtest iteration in the training loop.
    """
    client = _get_client()
    if client is None:
        return {"error": "Claude API not available"}

    cfg = load_config()

    prev_text = "This is the first iteration."
    if previous_metrics and previous_params:
        prev_text = (
            "Previous iteration ({n}):\n"
            "  Parameters: {params}\n"
            "  Win rate: {wr:.1%}, Sharpe: {sh:.2f}, PF: {pf:.2f}, "
            "Max DD: {dd:.1%}, Trades: {t}".format(
                n=iteration_number - 1,
                params=", ".join(f"{k}={v}" for k, v in previous_params.items()),
                wr=previous_metrics.get("win_rate", 0),
                sh=previous_metrics.get("sharpe_ratio", 0),
                pf=previous_metrics.get("profit_factor", 0),
                dd=previous_metrics.get("max_drawdown", 0),
                t=previous_metrics.get("total_trades", 0),
            )
        )

    param_str = ", ".join(f"{k}={v}" for k, v in parameters.items())
    prompt = (
        f"Training iteration {iteration_number} for strategy '{strategy_type}':\n\n"
        f"Current parameters: {param_str}\n"
        f"Candles: {candle_count}\n\n"
        f"Results:\n"
        f"  Final balance: ${metrics.get('final_balance', 0):,.2f}\n"
        f"  Total trades: {metrics.get('total_trades', 0)}\n"
        f"  Win rate: {metrics.get('win_rate', 0):.1%}\n"
        f"  Sharpe ratio: {metrics.get('sharpe_ratio', 0):.2f}\n"
        f"  Profit factor: {metrics.get('profit_factor', 0):.2f}\n"
        f"  Max drawdown: {metrics.get('max_drawdown', 0):.1%}\n"
        f"  Avg monthly return: {metrics.get('avg_monthly_return', 0):.2%}\n\n"
        f"{prev_text}\n\n"
        f"Trade summary:\n{trade_summary}\n\n"
        f"Analyze these results and suggest improved parameters. "
        f"Consider: which trades were profitable and why, what market conditions "
        f"caused losses, whether SL/TP levels are appropriate, and whether "
        f"indicator periods should be adjusted.\n\n"
        f"Respond with JSON:\n"
        f'{{\n'
        f'  "adjusted_parameters": {{{{"param_name": value, ...}}}},\n'
        f'  "reasoning": "why these changes should help",\n'
        f'  "data_feedback": {{\n'
        f'    "useful": ["indicators/timeframes that helped"],\n'
        f'    "exclude": ["data that added noise or hurt performance"]\n'
        f'  }},\n'
        f'  "confidence": 0.0-1.0,\n'
        f'  "risk_adjustments": {{\n'
        f'    "sl_atr_multiplier": <float or null>,\n'
        f'    "tp_atr_multiplier": <float or null>\n'
        f'  }}\n'
        f'}}'
    )

    try:
        system = (
            "You are an expert quantitative trading researcher. "
            "You analyze backtest results and iteratively improve strategy parameters. "
            "Be specific with parameter adjustments — provide exact values, not ranges. "
            "Consider overfitting risk: prefer robust improvements over curve-fitting. "
            "Always respond with valid JSON."
        )
        response = _review_create(client, cfg, system, prompt)
        text = _extract_text(response)
        parsed = _parse_json_response(text)
        if parsed is None:
            return {"error": "Could not parse response", "raw": text}
        parsed.setdefault("adjusted_parameters", parameters)
        parsed.setdefault("confidence", 0.5)
        return parsed
    except Exception as exc:
        logger.error("Claude training analysis error: %s", exc)
        return {"error": str(exc)}


def generate_training_report(iterations: list[dict]) -> dict:
    """Generate a final report summarizing an entire training run.

    Called after all iterations are complete.
    """
    client = _get_client()
    if client is None:
        return {"error": "Claude API not available"}

    cfg = load_config()

    if not iterations:
        return {"error": "No iterations to analyze"}

    iter_text = "\n".join(
        "Iteration {n} ({strat}, {sym}/{tf}):\n"
        "  Params: {params}\n"
        "  Win rate: {wr:.1%}, Sharpe: {sh:.2f}, PF: {pf:.2f}, "
        "Max DD: {dd:.1%}, Balance: ${bal:,.2f}"
        "{imp}".format(
            n=it.get("iteration_number", "?"),
            strat=it.get("strategy_type", "?"),
            sym=it.get("symbol", "?"),
            tf=it.get("timeframe", "?"),
            params=", ".join(f"{k}={v}" for k, v in it.get("parameters", {}).items()),
            wr=it.get("win_rate", 0) or 0,
            sh=it.get("sharpe_ratio", 0) or 0,
            pf=it.get("profit_factor", 0) or 0,
            dd=it.get("max_drawdown", 0) or 0,
            bal=it.get("final_balance", 0) or 0,
            imp=f"\n  Improvement: {it['improvement_pct']:+.1%}" if it.get("improvement_pct") is not None else "",
        )
        for it in iterations
    )

    prompt = (
        "Review this complete training run and provide a final assessment:\n\n"
        f"{iter_text}\n\n"
        "Respond with JSON:\n"
        '{\n'
        '  "best_iteration": <number>,\n'
        '  "best_params": {"param": value, ...},\n'
        '  "deploy_recommendation": "ready_to_deploy" | "needs_more_training" | "not_profitable",\n'
        '  "confidence": 0.0-1.0,\n'
        '  "improvements_found": ["list of key improvements discovered"],\n'
        '  "data_insights": ["what data/indicators were most valuable"],\n'
        '  "overfitting_risk": "low" | "medium" | "high",\n'
        '  "summary": "overall assessment"\n'
        '}'
    )

    try:
        system = (
            "You are a quantitative trading researcher reviewing a complete "
            "parameter optimization training run. Be honest about overfitting risk. "
            "Only recommend deployment if the results show robust, consistent improvement. "
            "Always respond with valid JSON."
        )
        response = _review_create(client, cfg, system, prompt)
        text = _extract_text(response)
        parsed = _parse_json_response(text)
        if parsed is None:
            return {"error": "Could not parse response", "raw": text}
        return parsed
    except Exception as exc:
        logger.error("Claude training report error: %s", exc)
        return {"error": str(exc)}


def analyze_closed_trade(trade_data: dict) -> dict:
    """Analyze a just-closed trade to record what went right/wrong.

    Uses Sonnet (fast model) since this runs on every trade close.
    Returns structured analysis for storage and later review.
    """
    client = _get_client()
    if client is None:
        return {"error": "Claude API not available"}

    cfg = load_config()

    symbol = trade_data.get("symbol", "?")
    side = trade_data.get("side", "?")
    entry = trade_data.get("entry_price", 0)
    exit_p = trade_data.get("exit_price", 0)
    sl = trade_data.get("stop_loss", 0)
    tp = trade_data.get("take_profit", 0)
    pnl = trade_data.get("pnl", 0)
    volume = trade_data.get("volume", 0)
    exit_type = trade_data.get("exit_type", "unknown")
    opened = trade_data.get("opened_at", "")
    closed = trade_data.get("closed_at", "")
    platform = trade_data.get("platform", "")
    candles_context = trade_data.get("candles_context", "")
    indicators_at_entry = trade_data.get("indicators_at_entry", "")
    indicators_at_exit = trade_data.get("indicators_at_exit", "")
    news_context = trade_data.get("news_context", "")

    # Calculate trade duration
    duration = ""
    if opened and closed:
        try:
            from datetime import datetime
            t_open = datetime.fromisoformat(str(opened)) if not isinstance(opened, datetime) else opened
            t_close = datetime.fromisoformat(str(closed)) if not isinstance(closed, datetime) else closed
            delta = t_close - t_open
            hours = delta.total_seconds() / 3600
            if hours < 1:
                duration = f"{int(delta.total_seconds() / 60)} minutes"
            else:
                duration = f"{hours:.1f} hours"
        except Exception:
            pass

    prompt = (
        f"Analyze this completed forex trade:\n\n"
        f"TRADE DETAILS:\n"
        f"  Symbol: {symbol}\n"
        f"  Side: {side.upper()}\n"
        f"  Entry: {entry:.5f}\n"
        f"  Exit: {exit_p:.5f}\n"
        f"  Stop Loss: {sl:.5f}\n"
        f"  Take Profit: {tp:.5f}\n"
        f"  Volume: {volume} lots\n"
        f"  P&L: ${pnl:+.2f}\n"
        f"  Exit Type: {exit_type}\n"
        f"  Duration: {duration}\n"
        f"  Platform: {platform}\n"
        f"  Opened: {opened}\n"
        f"  Closed: {closed}\n\n"
    )

    if indicators_at_entry:
        prompt += f"INDICATORS AT ENTRY:\n{indicators_at_entry}\n\n"
    if indicators_at_exit:
        prompt += f"INDICATORS AT EXIT:\n{indicators_at_exit}\n\n"
    if candles_context:
        prompt += f"PRICE ACTION AROUND TRADE:\n{candles_context}\n\n"
    if news_context:
        prompt += f"NEWS EVENTS DURING TRADE:\n{news_context}\n\n"

    prompt += (
        f"Provide a thorough post-trade analysis. Be specific about what the market "
        f"did and why. If it was a loss, identify the specific reason (bad entry timing, "
        f"news event, trend reversal, stop too tight, etc).\n\n"
        f"Respond with JSON:\n"
        f'{{\n'
        f'  "outcome": "win" or "loss",\n'
        f'  "pnl_assessment": "brief description of what happened",\n'
        f'  "entry_quality": "assessment of entry timing and conditions",\n'
        f'  "exit_quality": "assessment of how the trade exited",\n'
        f'  "market_context": "what was happening in the market during this trade",\n'
        f'  "news_impact": "any news events that affected the trade, or none",\n'
        f'  "what_went_right": ["list of positives"],\n'
        f'  "what_went_wrong": ["list of negatives"],\n'
        f'  "lesson": "key takeaway for future trades",\n'
        f'  "confidence_in_analysis": 0.0-1.0\n'
        f'}}'
    )

    try:
        response = client.messages.create(
            model=cfg.claude.model,  # Sonnet — fast, runs on every trade close
            max_tokens=2048,
            temperature=0.3,
            system=(
                "You are a forex trade analyst reviewing completed trades. "
                "Be specific and honest. For losses, identify the exact market condition "
                "or decision that caused the loss. For wins, identify what worked well. "
                "Reference the actual price levels, indicators, and news events provided. "
                "Always respond with valid JSON."
            ),
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.content[0].text
        parsed = _parse_json_response(text)
        if parsed is None:
            return {"error": "Could not parse response", "raw": text}
        if isinstance(parsed, list):
            parsed = parsed[0] if parsed and isinstance(parsed[0], dict) else {}
        parsed.setdefault("outcome", "win" if pnl >= 0 else "loss")
        parsed.setdefault("confidence_in_analysis", 0.5)
        return parsed
    except Exception as exc:
        logger.error("Trade analysis error: %s", exc)
        return {"error": str(exc)}


def compute_price_summary(candles: list[dict]) -> dict:
    """Compute basic price statistics from candle data.

    Preserved from claude_workflow.py for backward compatibility.
    """
    if not candles:
        return {}

    closes = [c["close"] for c in candles]
    highs = [c["high"] for c in candles]
    lows = [c["low"] for c in candles]

    avg_price = sum(closes) / len(closes)
    price_range = max(highs) - min(lows)

    variance = sum((c - avg_price) ** 2 for c in closes) / len(closes)
    volatility = variance ** 0.5

    recent = candles[-min(20, len(candles)):]

    return {
        "open": f"{recent[0]['open']:.5f}",
        "high": f"{max(c['high'] for c in recent):.5f}",
        "low": f"{min(c['low'] for c in recent):.5f}",
        "close": f"{recent[-1]['close']:.5f}",
        "avg": f"{avg_price:.5f}",
        "range": f"{price_range:.5f}",
        "volatility": f"{volatility:.5f}",
    }
