"""Aggregate recent trade lessons from closed trade analyses.

Pulls `trade_analysis` JSON blobs from LiveTrade and formats them as
context that can be injected into signal evaluation prompts. The goal
is to give Claude memory of recent successes and failures so it can
use judgment rather than following rigid rules.
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Any

from db import get_session
from models.signal import LiveTrade

logger = logging.getLogger(__name__)

# Trades closed before this date were generated by the prior rigid-rules
# system where Claude was forced into trades by single-indicator triggers.
# Those lessons describe mistakes Claude did not choose using judgment, so
# feeding them back as "things to avoid" inherits critiques of a different
# decision regime. Only trades closed on/after this date are included in
# the lessons feed.
#
# The switchover happened when the service was first restarted with the
# considerations-based code (April 15 ~5pm PT = April 16 00:08 UTC). Using
# April 16 00:00 UTC as a clean cutoff.
SWITCHOVER_DATE = datetime(2026, 4, 16, 0, 0, 0, tzinfo=timezone.utc)


def _extract_list(analysis: dict, key: str) -> list[str]:
    """Pull a list-of-strings field from a trade_analysis blob, handling edge cases."""
    val = analysis.get(key)
    if isinstance(val, list):
        return [str(x).strip() for x in val if x]
    if isinstance(val, str) and val.strip():
        return [val.strip()]
    return []


def _recent_closed_trades(symbol: str | None, days: int, limit: int) -> list[LiveTrade]:
    """Return recent closed trades (optionally filtered to one symbol) with analysis.

    Pre-switchover trades are excluded — see SWITCHOVER_DATE docstring above.
    """
    session = get_session()
    try:
        window_cutoff = datetime.now(timezone.utc) - timedelta(days=days)
        # Use the later of SWITCHOVER_DATE and the rolling window — this way
        # immediately after the switchover we only see judgment-era trades,
        # and once enough time passes the rolling window takes over.
        cutoff = max(window_cutoff, SWITCHOVER_DATE)
        q = (
            session.query(LiveTrade)
            .filter(
                LiveTrade.status == "closed",
                LiveTrade.trade_analysis.isnot(None),
                LiveTrade.closed_at >= cutoff,
            )
        )
        if symbol:
            q = q.filter(LiveTrade.symbol == symbol)
        return q.order_by(LiveTrade.closed_at.desc()).limit(limit).all()
    finally:
        session.close()


def get_lessons_for_symbol(
    symbol: str,
    *,
    days: int = 14,
    max_losses: int = 5,
    max_wins: int = 3,
    include_general: bool = True,
    max_general: int = 3,
) -> dict[str, Any]:
    """Return structured lessons for a symbol based on recent closed trades.

    Output shape:
      {
        "symbol_losses":  [ {"pnl": -50.5, "lesson": "...", "wrong": [...]} ],
        "symbol_wins":    [ {"pnl":  +80.0, "right": [...], "lesson": "..."} ],
        "general_losses": [ {"symbol": "EURUSD", "pnl": -90.0, "lesson": "..."} ],
        "total_trades":    int,
        "symbol_win_rate": float | None,
        "symbol_avg_pnl":  float | None,
      }
    """
    sym_trades = _recent_closed_trades(symbol, days, max_losses + max_wins + 10)

    losses: list[dict] = []
    wins: list[dict] = []
    total_pnl = 0.0
    win_count = 0

    for t in sym_trades:
        analysis = t.trade_analysis or {}
        if not isinstance(analysis, dict):
            continue
        pnl = t.pnl or 0.0
        total_pnl += pnl
        entry = {
            "pnl": round(pnl, 2),
            "side": t.side,
            "lesson": (analysis.get("lesson") or "").strip(),
            "wrong": _extract_list(analysis, "what_went_wrong"),
            "right": _extract_list(analysis, "what_went_right"),
            "entry_quality": (analysis.get("entry_quality") or "").strip(),
            "closed_at": t.closed_at.isoformat() if t.closed_at else None,
        }
        if pnl >= 0:
            win_count += 1
            if len(wins) < max_wins:
                wins.append(entry)
        else:
            if len(losses) < max_losses:
                losses.append(entry)

    total = len(sym_trades)
    win_rate = (win_count / total) if total else None
    avg_pnl = (total_pnl / total) if total else None

    general: list[dict] = []
    if include_general:
        # Broader cross-pair lessons: any recent loss with a non-trivial lesson
        all_trades = _recent_closed_trades(None, days, 30)
        seen_lessons: set[str] = set()
        for t in all_trades:
            if len(general) >= max_general:
                break
            if t.symbol == symbol:
                continue  # already covered in symbol_losses
            analysis = t.trade_analysis or {}
            if not isinstance(analysis, dict):
                continue
            pnl = t.pnl or 0.0
            if pnl >= 0:
                continue
            lesson = (analysis.get("lesson") or "").strip()
            if not lesson:
                continue
            # Deduplicate near-identical lessons
            key = lesson[:60].lower()
            if key in seen_lessons:
                continue
            seen_lessons.add(key)
            general.append({
                "symbol": t.symbol,
                "side": t.side,
                "pnl": round(pnl, 2),
                "lesson": lesson,
            })

    return {
        "symbol_losses": losses,
        "symbol_wins": wins,
        "general_losses": general,
        "total_trades": total,
        "symbol_win_rate": win_rate,
        "symbol_avg_pnl": avg_pnl,
    }


def format_lessons_for_prompt(symbol: str, **kwargs) -> str:
    """Return a human-readable lessons block ready to drop into a prompt.

    When there are no post-switchover lessons yet, returns an explicit
    "fresh memory" message so Claude knows it's working from first principles
    rather than being asked to guess at prior context.
    """
    data = get_lessons_for_symbol(symbol, **kwargs)

    losses = data["symbol_losses"]
    wins = data["symbol_wins"]
    general = data["general_losses"]
    total = data["total_trades"]

    if not (losses or wins or general):
        return (
            "RECENT TRADE MEMORY: No closed trades yet under the current "
            "judgment-based system. Use the considerations framework and current "
            "indicators to make a clean first-principles assessment. You are not "
            "inheriting critiques from any prior decision regime — trade each "
            "setup on its own merits. HOLD is still the default when conditions "
            "are marginal, but do not manufacture reasons to avoid a clean setup."
        )

    lines: list[str] = []
    lines.append(f"RECENT TRADE MEMORY ({symbol}, last {kwargs.get('days', 14)} days):")
    lines.append(
        "  IMPORTANT: These lessons describe outcomes from YOUR recent judgment-based "
        "trades. Treat them as data points about patterns that worked or failed — not "
        "as prohibitions. A setup that rhymes with a past loss is worth extra scrutiny, "
        "but is NOT automatically disqualified if current context is genuinely different."
    )

    if total:
        wr = data["symbol_win_rate"]
        avg = data["symbol_avg_pnl"]
        wr_txt = f"{wr:.0%}" if wr is not None else "n/a"
        avg_txt = f"${avg:+.2f}" if avg is not None else "n/a"
        lines.append(f"  Stats: {total} closed trades, win rate {wr_txt}, avg P&L {avg_txt}")

    if losses:
        lines.append("")
        lines.append(f"  Recent LOSSES — patterns to scrutinize (not forbid):")
        for i, l in enumerate(losses, 1):
            lesson = l["lesson"] or "(no lesson recorded)"
            wrong = l["wrong"]
            lines.append(f"    {i}. [{l['side'].upper()} P&L ${l['pnl']:+.2f}] {lesson}")
            if wrong:
                # Show top 2 specific issues
                for w in wrong[:2]:
                    lines.append(f"       - {w}")

    if wins:
        lines.append("")
        lines.append(f"  Recent WINS — patterns that worked:")
        for i, w in enumerate(wins, 1):
            lesson = w["lesson"] or "(no lesson recorded)"
            right = w["right"]
            lines.append(f"    {i}. [{w['side'].upper()} P&L ${w['pnl']:+.2f}] {lesson}")
            if right:
                for r in right[:2]:
                    lines.append(f"       + {r}")

    if general:
        lines.append("")
        lines.append("  Recent losses on OTHER pairs (broader patterns):")
        for i, g in enumerate(general, 1):
            lines.append(
                f"    {i}. [{g['symbol']} {g['side'].upper()} ${g['pnl']:+.2f}] {g['lesson']}"
            )

    lines.append("")
    lines.append(
        "  Use these as context, not as blockers. Your job is to assess THIS specific "
        "moment on its own merits — the framework, the current indicators, the candle "
        "structure, and the broader market tone. HOLD when genuinely uncertain; take "
        "the trade when the setup is clean, even if surface features remind you of "
        "a past loss."
    )
    return "\n".join(lines)
